name: fordev
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  http:
  flutter_launcher_icons:
  provider:
  equatable: 
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 
  mockito: 
  faker: 
  test_api: 


flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptative_icon_background: lib/ui/assets/icon/background.png
  adaptative_icon_foreground: lib/ui/assets/icon/foreground.png
