name: cuidapet_curso
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
scripts:
  build_runner_compile: flutter pub run build_runner build --delete-conflicting-outputs
  build_runner_watch: flutter pub run build_runner watch --delete-conflicting-outputs
dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.7+3
  connectivity: ^0.4.9
  image_picker: ^0.6.7
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^3.0.1
  flutter_screenutil: ^1.1.0
  get: ^3.15.0
  flutter_icons: ^1.1.0
  flutter_dotenv: ^2.1.0
  intl: ^0.16.1
  url_launcher: ^5.4.10
  flutter_calendar_carousel: ^1.4.12
  json_annotation: ^3.0.1
  sqflite: ^1.3.0+2
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.16
  path: ^1.6.4
  flutter_typeahead: ^1.8.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  flutter_facebook_login: ^3.0.0
  flutter_local_notifications: ^1.4.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  mobx_codegen: ^1.1.2
  mockito: ^4.1.1
  pedantic: ^1.9.0
  flutter_modular_test: ^1.0.0
flutter:
  uses-material-design: true